


game: main.c LoadGame.c Events.c CreateTex.c CollisionDetection.c Render.c gameStatus.c Game.h
	i686-w64-mingw32-gcc main.c LoadGame.c Events.c CreateTex.c CollisionDetection.c Render.c gameStatus.c Game.h -w -Dsrandom=srand -Drandom=rand -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -o game.exe -lm -I.
