


game: main.c LoadGame.c Events.c CreateTex.c CollisionDetection.c Render.c gameStatus.c Game.h
	gcc main.c LoadGame.c Events.c CreateTex.c CollisionDetection.c Render.c gameStatus.c Game.h -w -Dsrandom=srand -lSDL2main -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -o game -lm -I.
